config/routes.rb
Fritter::Application.routes.draw do

  resources :hashtags
  get "statistics/index"
  get "statistics" => "statistics#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :posts
    end
  end

  get "welcome/index"

  root to: 'welcome#index'

  get 'all' => 'posts#index'

  
  get 'users/:username/posts' => 'users#show'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  acts_as_taggable
  
  belongs_to :post
  belongs_to :user

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_taggable

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true,
  length: {minimum: 5}

  validates :owner, presence: true,
  length: {minimum: 5}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :get_idx_post, only: [:create, :destroy]
  before_action :get_idx_comment, only: [:destroy]

  def index
    @comments = Comment.all
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  def create
    @comment = 
      @post.comments.create(comment_params)
    @comment.save
    redirect_to post_path(@post)
  end

  private
  
    def comment_params
      params[:comment].permit(:commenter, :body)
    end

    def get_idx_post
      @post = Post.find(params[:post_id])
    end

    def get_idx_comment
      @comment = @post.comments.find(params[:id])
    end
  
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  before_action :get_posts_by_comments
  before_action :get_tag_param, only: [:show]

  def index
    @posts = Post.all(:order => "created_at").select{|p| p.tag_list.count > 0}
  end

  def show
    @posts = @posts.select{|p| p.tag_list.include? @tag }
  end

  private
    def get_posts_by_comments
      @posts = Post.all :joins => :comments, :group => 'posts.id', :order => 'count(*)'
      @posts = (@posts + Post.all.select{|p| p.comments.count == 0}).take(10)
    end

    def get_tag_param
      @tag = params[:id]
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :get_idx_post, :only => [:show, :edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
  end

  def new
    if not user_signed_in?
      redirect_to new_user_session_path
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(post_params)
    @post.owner = current_user.email
    @post.user_id = current_user.id
    @post.tag_list = filter_hashtags(@post.text)
    if @post.save
        redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def edit
  end

  def index
    @posts = Post.all.reverse #Order them from new -> old
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
      tags = filter_hashtags(@post.text)
      if not tags.nil? || tags.empty?
        @post.tag_list = tags
        @post.save
      end
    else
      render 'edit'
    end
  end

  private
    def get_idx_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :text)
    end
    
    def filter_hashtags(text)
      (text.split.select{|w| w.starts_with?('#')}).uniq
    end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  def index
    @posts     = Post.all(:joins => :comments, :group => 'posts.id', :order => 'count(*)')
    @users     = User.all(:joins => :posts, :group => 'users.id', :order => 'count(*)')
    tags      = get_hashtags(@posts + Post.all.select{|p| p.comments.count == 0})
    utags = tags.uniq
    @tagcounts = utags.zip(utags.map{|tag| tags.count(tag)})
  end

  private
    def get_hashtags(posts)
      htags = []
      posts.each do |post|
        post.tag_list.each do |tag|
          htags.push(tag)
        end
      end
      return htags.sort{|x, y| htags.count(x) <=> htags.count(y)}
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def update
    super
  end

  def trim_username(username)
    username[0, username.index('@')]
  end

  def create
    super
    @user.username = trim_username params[:user].require(:email)
    @user.save
  end

  def posts
    @user = User.find(params[:id])
    @posts = @user.posts
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.where(username: params[:id])[0]
    @posts = @user.posts
  end

  def posts
    @user = User.where(username: params[:id])[0]
    @posts = @user.posts
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.haml
%p
  %strong
    %i
      - uname = comment.commenter[0, comment.commenter.index('@')]
      = link_to uname, posts_user_path(User.find_by_email(comment.commenter))
    said:  
  %br
  = comment.body
  %br
  %small
    = comment.created_at
    - if user_signed_in?
      - if current_user.email == comment.commenter || current_user == @post.user
        = link_to 'Delete', [comment.post, comment],  method: :delete, data: {confirm: 'Are you sure?'}
    

app/views/comments/index.html.erb
<h1>All Comments</h1>

<%= render Comment.all %>

app/views/hashtags/index.html.haml
%h1 Hashtags

%h3 Newest Hashtagged Posts

- @posts.each do |p|
  - p.tag_list.each do |tag|
    = link_to tag, hashtag_path tag
    in
    = link_to p.text, post_path p
    %br

app/views/hashtags/show.html.haml
%h1 
  = @tag

%h3 Top Tagged Posts
%p
  - @posts.each do |p|
    = link_to p.title, post_path(p)
    = "(" + pluralize(p.comments.count.to_s, "comment") + ") by "
    = link_to p.user.username, p.user
    %br

app/views/layouts/application.html.haml
<!DOCTYPE html>

%html
  %head
    %title Fritter
    = stylesheet_link_tag "application", media: "all", "data-turbolinks=track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag :defaults
    = csrf_meta_tags
  %body
    .container
      .navbar.navbar-default
        .navbar-header
          = link_to "Fritter", root_path, :class => "navbar-brand"
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              %li
                = link_to current_user.email, posts_user_path(current_user)
            %li
              - if user_signed_in?
                = link_to "Sign Out", destroy_user_session_path, :method => :delete
              - else
                = link_to "Sign In", user_session_path
            %li
              = link_to "All Posts", posts_path
            %li
              = link_to "Statistics", statistics_path
          %ul.nav.navbar-nav.navbar-right
      
      .jumbotron
        - if flash[:notice]
          %p.notice= notice
        - if flash[:alert]
          %p.alert= alert
        = yield

app/views/posts/_allposts.html.haml
- if @posts.count == 0
  %strong There are no posts yet.
- else
  %table
    - @posts.each do |post|
      %tr
        %td
          %small
            %i= post.created_at.to_formatted_s(:short) + ":"
          = post.title
        %td
          %small
            %i by
            = link_to post.user.username, user_path(post.user)
        %td
          %small= link_to "View (" + pluralize(post.comments.count, "comment") + ")", post

%br

app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #errorExplanation
      %h3= pluralize(@post.errors.count, "error") + ":"
      %ul
        -@post.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title
    %br
    = f.text_field :title

  %p
    = f.label :text
    %br
    = f.text_area :text

  %p
    = f.submit

app/views/posts/_posttext.html.haml
%p
  - @post.text.split(' ').each do |word|
    - if word[0] == '@'
      - us = User.find_by_username(word[1..word.length])
      - if us.nil?
        = word
      - else
        = link_to word, posts_user_path(us)
    - else 
      - if word[0] == '#'
        = link_to word, hashtag_path(word)
      - else
        = word

app/views/posts/clear.html.haml
%h1 All posts cleared.

= link_to "All Posts", posts_path

app/views/posts/edit.html.haml
%h1 
  Edit Post
  = @post.id

= render 'form'

= link_to 'All Posts', posts_path

app/views/posts/index.html.haml
%h1 All Posts

= render 'allposts'

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

= link_to 'All Posts', posts_path

app/views/posts/show.html.haml
%p
  %h1= @post.title

-if user_signed_in? && @post.owner == current_user.email
  = link_to 'Edit', edit_post_path(@post)
  = link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}

= render 'posttext'

%p
  %small
    %i Last Edited 
    = @post.created_at
  %i by 
  - uname = @post.user.username
  = link_to uname, posts_user_path(User.find_by_username uname) 

%hr

- if @post.comments.empty?
  %h3 No Comments
- else
  %h3= pluralize(@post.comments.count, "Comment") + ":"
  = render @post.comments

%hr

%h3 Add Comment
- if not user_signed_in?
  %i= (link_to "Sign in", new_user_session_path) + " to post comments!"
  %br
  %br
- else
  = form_for ([@post, @post.comments.build]) do |f|
    %p
      = f.label :commenter
      = f.text_field :commenter, value: current_user.email, :readonly => true
    %p
      = f.label :body
      = f.text_area :body
    %p
      = f.submit

= link_to 'All Posts', posts_path
    

app/views/statistics/_comments_by_user_chart.html.erb
<div id="commentsbypostchart" style="width:100%; height:400px;"></div>

<script>
  $(function () 
  { 
    $('#commentsbypostchart').highcharts(
    {
        chart: 
        {
            type: 'bar'
        },
        title: 
        {
            text: 'Comments By Post'
        },
        xAxis: 
        {
            categories: ['Comments'],
            minTickInterval: 1
        },
        yAxis: 
        {
            title: 
            {
                text: 'Post'
            },
            minTickInterval: 1
        },
        series:
        [
          <% @posts.take(10).each do |post| %>
	  {
	    name: '<%= post.title + " by " + post.user.username%>',
	    data: [<%= post.comments.count %>]
	  },
	  <% end %>
        ]
    });
  });
</script>

app/views/statistics/_hashtag_chart.html.erb
<div id="hashtagschart" style="width:100%; height:400px;"></div>

<script>
  $(function () 
  { 
    $('#hashtagschart').highcharts(
    {
        chart: 
        {
            type: 'bar'
        },
        title: 
        {
            text: 'Top Hashtags'
        },
        xAxis: 
        {
            categories: ['Hashtag'],
            minTickInterval: 1
        },
        yAxis: 
        {
            title: 
            {
                text: 'Posts'
            },
            minTickInterval: 1
        },
        series:
        [
          <% @tagcounts.take(10).each do |tc| %>
	  {
	    name: '<%= tc[0] %>',
	    data: [<%= tc[1] %>]
	  },
	  <% end %>
        ]
    });
  });
</script>

app/views/statistics/_posts_by_user_chart.html.erb
<div id="postsbyuserchart" style="width:100%; height:400px;"></div>
<script>
  $(function () 
  { 
    $('#postsbyuserchart').highcharts(
    {
        chart: 
        {
            type: 'bar'
        },
        title: 
        {
            text: 'Posts By User'
        },
        xAxis: 
        {
            categories: ['Posts'],
            minTickInterval: 1
        },
        yAxis: 
        {
            title: 
            {
                text: 'User'
            },
            minTickInterval: 1
        },
        series:
        [
          <% @users.take(10).each do |user| %>
	  {
	    name: '<%= user.username %>',
	    data: [<%= user.posts.count.to_s %>]
	  },
	  <% end %>
        ]
    });
  });
</script>

app/views/statistics/index.html.haml
%h1 Statistics

%h3 Top Posters
= render 'posts_by_user_chart'

%h3 Most Popular Posts
= render 'comments_by_user_chart'

%h3 Top Hashtags
= render 'hashtag_chart' 

app/views/users/posts.html.haml
%h1= @user.username

= render 'posts/allposts'

- if user_signed_in?
  - if current_user.username == @user.username
    = link_to 'New Post', new_post_path

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
%h1= @user.username

= render :partial => 'posts/allposts'

app/views/welcome/index.html.erb
<h1>Welcome To Fritter</h1>
<p>Better than Twitter... I promise!</p>
<%= link_to 'Go to Posts', posts_path %>